Flatten historic
thesocialcoin/ds-Alerts pull request #8
Opened 2023-11-17 11:40 UTC by wilberquito

2023-11-20 14:01 UTC, quimdt approved these changes
Nice job :tada: 

I just make observations about the structure of the code and how to improve the readability . The algorithm is nice. May is good idea when comparing two versions of the algortihms having in separated classes.

2023-11-20 14:14 UTC, wilberquito commented on src/alerts/time_series.py
> +            lower_bound = median - (self.quantile * 1.4826 * mad)
@quimdt this was made by Alex HAHAH it as a is a scaling facto used when working with the mean absolute deviation (MAD).  When the dataset follows a normal distribution, the expected value of the MAD is related to the standard deviation (σ) of the distribution.

2023-11-20 14:17 UTC, wilberquito commented on src/alerts/time_series.py
> +class AnomalyTS():
@quimdt True

2023-12-01 14:43 UTC, oscar-delgado requested changes
Nice! Once the class names are reviewed, we can test it out in the code itself!

2023-12-01 14:43 UTC, oscar-delgado commented on src/alerts/anomaly.py
> +            if value > upper_bound_limits[i]:
I don't fully understand the benefits of doing 4 loops instead of one

2023-12-01 14:43 UTC, oscar-delgado commented on src/alerts/plot.py
Maybe this shouldn't be in the library source since this isn't needed for the execution

2023-12-01 14:43 UTC, oscar-delgado commented on src/alerts/time_series.py
The class TimeSeries is used among other projects, so its name and main functions should remain the same for not breaking compatibility with other parts of the code. Can you refactor it to do so? If you need more info about what is been used and what not, we can talk about it!

2023-12-01 14:46 UTC, oscar-delgado commented on src/alerts/preprocess.py
> +    assert "date" in data.columns
Assert statements are reserved for testing purposes as we can not control it. Use Exception or a custom exception

2023-12-01 15:06 UTC, quimdt commented on src/alerts/dataclasses.py
> +        self.upper_bound = ub
Define it better in that way, init method is used to add extra logic
```suggestion
class LimitInterval:
    lower_bound: float
    upper_bound float
```

2023-12-04 14:28 UTC, merged